build:
	g++ -std=c++11 -O3 kim.cpp -o kim
	g++ -std=c++11 -O3 portal.cpp -o portal 

run-p1:
	./kim

run-p2:
	./portal

clean:
	rm portal kim 

pack:
	zip 325CA_NeatuDarius_Tema2.zip kim.cpp portal.cpp Makefile README 