build:
	g++ -Wall -Wextra joc.cpp -o joc
	g++ -Wall -Wextra cablaj.cpp -o cablaj
run-p1:
	./joc

run-p2:
	./evaluare

run-p3:
	./cablaj

clean: joc 
	rm joc cablaj

pack:
	zip 325CA_NeatuDarius_Tema1.zip joc.cpp cablaj.cpp Makefile README